### ISSUE TITLE
How to specify which game?

### ISSUE THREAD

**Issue by yeethawnathan** [turtleisaac/PokEditor#4]
So, I'm relatively new to the hacking area, and this seemed like the most promising program for adding in pokemon, which I've been trying to do for a while.

The only problem is, the file has gens 4-6 listed, and I'm not sure how to only find the files for Pokemon Platinum, which I've been trying to mod.

What should I do?

**Comment by turtleisaac** [comment]
Hi, can you please provide a more in-depth explanation of what you are encountering issues with? I don't quite understand.

Also, it would help if you joined this Discord server: https://discord.gg/cTKQq5Y

It is much easier for me to help people there.

**Comment by turtleisaac** [comment]
Also, adding in new Pokemon is not something that can be accomplished easily. It takes a lot of technical knowledge and work with custom asm (assembly code). If you join the Discord server, we can talk more about it.

**Comment by yeethawnathan** [comment]
I'm very sorry, I'm kind of a noob when it comes to this and didn't realize how hard it was, I realized that I wasn't having issues with your system, I just didn't know what I was doing.

Thank you for trying to help, and sorry for that.

**Comment by yeethawnathan** [comment]
I'm very sorry, I'm kind of a noob when it comes to this and didn't realize how hard it was, I realized that I wasn't having issues with your system, I just didn't know what I was doing.

Thank you for trying to help, and sorry for that.
